### PR TITLE
Find git dir

### PR DESCRIPTION
**Pull request by ghost**
Now uses the FileRepositoryBuilder to find the git repository, bump jgit and increment the version number.

### CODE REVIEW

**Comment by md-5** [comment]
What's the advantage?

**Comment by ghost** [comment]
Imagine the following project structure

```
parent-project
|-- .git
|-- parent-pom.xml
|-- sub-project-1
|    |-- sub-project-1-pom.xml
|-- sub-project-2
|    |-- sub-project-2-pom.xml
```

Without the FileRepositoryBuilder you have to specify the .git directory in every sub-project, but the FileRepositoryBuilder searches automatically for the directory in the parent folders and in the folder itself.

**Comment by md-5** [comment]
Thanks

**Comment by ghost** [comment]
No problem :)

Do you know, how long it takes to appear in the central repo?

**Comment by md-5** [comment]
Only releases are deployed. If you need to use it in your projects, build + install it locally.

**Pull request closed without merging**
